apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Template for monkey-ops Agent
    iconClass: icon-openjdk
    tags: instant-app,agent
  name: monkey-ops
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
    labels:
      app_name: ${APP_NAME}
  spec:
    selector:
      app_name: ${APP_NAME}
    type: ClusterIP
    ports:
    - name: web
      port: 8080
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app_name: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app_name: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app_name: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: APP_NAME
            value: ${APP_NAME}
          - name: PROJECT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
#            value: ${PROJECT_NAME}
          - name: INTERVAL
            value: ${INTERVAL}
          - name: MODE
            value: ${MODE}
          - name: TZ
            value: ${TZ}
          image: produban/monkey-ops:latest
          imagePullPolicy: IfNotPresent
          name: ${APP_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: 64Mi
            request:
              memory: 64Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /opt/metadata
            name: podinfo
            readOnly: false
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        serviceAccount: ${SA_NAME}
        serviceAccountName: ${SA_NAME}
        volumes:
        - metadata:
            items:
            - fieldRef:
                fieldPath: metadata.labels
              name: labels
            - fieldRef:
                fieldPath: metadata.annotations
              name: annotations
          name: podinfo
  status: {}
parameters:
- description: Application name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: monkey-ops
- description: Project name
  displayName: Project Name
  name: PROJECT_NAME
  required: true
  value: monkey-ops
- description: Service Account name
  displayName: Service Account name
  name: SA_NAME
  required: true
  value: monkey-ops
- description: Time interval between each actuation of operator monkey
  displayName: Time interval between each actuation of operator monkey. It must be in seconds
  name: INTERVAL
  required: true
- description: Execution Mode, It must be "background", i.e., it runs nonstop, or "rest", i.e., it executes via API Rest.
  displayName: Execution Mode, It must be "background", i.e., it runs nonstop, or "rest", i.e., it executes via API Rest.
  name: MODE
  required: true
  value: rest
- description: TimeZone for the running containers.
  displayName: TimeZone
  name: TZ
  value: Europe/Helsinky
